POSTGRES_USERNAME: user
POSTGRES_PASSWORD: dbpassword
POSTGRES_HOST: 192.168.1.15
POSTGRES_PORT: 5432
POSTGRES_DATABASE: securedocdb

CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:8085
JWT_EXPIRATION: 432_000_000
JWT_SECRET: YsEuUuLYh/srTGduusZgZksTcBS7O0lK8x29W7If8MD11HJkvjjQiXKkDdRbbu8w0sWZ+Y9mqBh6TsYPkwAeBw==
